// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA92vZQ6OgL2e29R_nZYaRvlhBqQ7t4l0A',
    appId: '1:654701318393:web:2f626a459d02d586695228',
    messagingSenderId: '654701318393',
    projectId: 'runoogers',
    authDomain: 'runoogers.firebaseapp.com',
    storageBucket: 'runoogers.appspot.com',
    measurementId: 'G-3DVV2LK6R1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgO6mqrt2UvshLiKzsIckUlmYksrwPxdY',
    appId: '1:654701318393:android:21ef331a359d5eca695228',
    messagingSenderId: '654701318393',
    projectId: 'runoogers',
    storageBucket: 'runoogers.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZvTW0tGPaFb_XqT_7cdpMi7dXeIc9tC8',
    appId: '1:654701318393:ios:8f3a1dfdfff9e68d695228',
    messagingSenderId: '654701318393',
    projectId: 'runoogers',
    storageBucket: 'runoogers.appspot.com',
    iosBundleId: 'com.example.runningapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZvTW0tGPaFb_XqT_7cdpMi7dXeIc9tC8',
    appId: '1:654701318393:ios:8f3a1dfdfff9e68d695228',
    messagingSenderId: '654701318393',
    projectId: 'runoogers',
    storageBucket: 'runoogers.appspot.com',
    iosBundleId: 'com.example.runningapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA92vZQ6OgL2e29R_nZYaRvlhBqQ7t4l0A',
    appId: '1:654701318393:web:0c1ddfc585a6c5f7695228',
    messagingSenderId: '654701318393',
    projectId: 'runoogers',
    authDomain: 'runoogers.firebaseapp.com',
    storageBucket: 'runoogers.appspot.com',
    measurementId: 'G-FCGQCPPN6F',
  );
}
